In [1]:
import numpy as np
import pandas as pd
import sys
import os
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [6]:
DPP_path = Path.cwd()
Base_path = DPP_path.parent
Data_path = Base_path / 'Data'
AnMat_path = Base_path / 'Analytical Materials'
Fid_Uid_path = Data_path / 'df_Fid_Uid_link_hack.csv'
Uid_data_path = Data_path / 'df_Uid_data_hack.csv'
Uid_payment_path = Data_path / 'df_Uid_payment_hack.csv'
AnMat_paths = [AnMat_path / k for k in AnMat_path.iterdir()]

In [23]:
df_Fid_Uid = pd.read_csv(Fid_Uid_path, delimiter = ';')
df_Uid_data = pd.read_csv(Uid_data_path, delimiter = ';')
df_Uid_payment = pd.read_csv(Uid_payment_path, delimiter = ';')
df_Uid_data

,SYNTHETIC_U,ORG_TYPE,OKFS_NAME,COMPANY_AGE_YEARS_GRADATION,ECO_MARK_LABEL,MAINOKVED_CODE,MAINOKVED_NAME,NEGATIVEMARK,AMOUNT_WORKERS_FNS_GRADATION,AMOUNT_WORKERS_SPARK_GRADATION,...,CL_PRODUCT_LEA_MARK,CL_PRODUCT_DEP_MARK,CL_PRODUCT_ZPP_MARK,FTS_FLAG,FTS_COUNTRY_NAME,FACTORING_MARK,REVENUE_COMPANY,GROUP_ID,CITY,REGION
0,U_67,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Рождение,46.51,"Торговля оптовая компьютерами, периферийными у...",0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,1.364930e+05,group_134463_sb,г. Новосибирск,Новосибирская область
1,U_76,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Оптимизация,52.29,"Деятельность вспомогательная прочая, связанная...",0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,8.903765e+08,group_90087_sb,г. Новосибирск,Новосибирская область
2,U_80,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Оптимизация,25.61,Обработка металлов и нанесение покрытий на мет...,0.0,16-100,NaN,...,1.0,0.0,0.0,0.0,NaN,0.0,1.423218e+09,group_104611_sb,г. Екатеринбург,Свердловская область
3,U_81,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Оптимизация,46.34.2,"Торговля оптовая алкогольными напитками, включ...",0.0,16-100,NaN,...,1.0,0.0,1.0,0.0,NaN,0.0,2.640763e+08,group_134617_sb,г. Екатеринбург,Свердловская область
4,U_84,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Бизнес в новой реальности,46.90,Торговля оптовая неспециализированная,0.0,16-100,NaN,...,1.0,1.0,1.0,0.0,NaN,0.0,1.331906e+09,group_102859_sb,г. Курган,Курганская область
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85520,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,8-15,Бизнес в новой реальности,52.29,"Деятельность вспомогательная прочая, связанная...",0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,5.142700e+04,group_90099_sb,г. Самара,Самарская область
85521,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,0-3,NaN,46.73,"Торговля оптовая лесоматериалами, строительным...",0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,7.397578e+08,group_90293_sb,г. Москва,Москва
85522,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Бизнес в новой реальности,68.32.1,Управление эксплуатацией жилого фонда за возна...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,4.429000e+04,group_86361_sb,г. Тольятти,Самарская область
85523,U_428697,КОММ_ОРГ,СОБСТВЕННОСТЬ ИНОСТРАННЫХ ГРАЖДАН И ЛИЦ БЕЗ ГР...,0-3,NaN,47.91,Торговля розничная по почте или по информацион...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,9.502302e+07,group_92057_sb,г. Москва,Москва
85524,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,8-15,Бизнес в новой реальности,68.20.2,Аренда и управление собственным или арендованн...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,2.757700e+04,group_42134_sb,г. Тольятти,Самарская область

In [12]:
df_Fid_Uid.isna().sum()

SYNTHETIC_F     0
CITY_NAME      14
RC_NAME        14
SYNTHETIC_U     0
dtype: int64

In [16]:
df_Fid_Uid[df_Fid_Uid.isna().any(axis=1)]

      SYNTHETIC_F CITY_NAME RC_NAME SYNTHETIC_U
85        F_44770       NaN     NaN     U_94386
166       F_80363       NaN     NaN    U_165802
1107      F_47724       NaN     NaN    U_154983
1939      F_31346       NaN     NaN    U_191995
1961      F_17564       NaN     NaN     U_32547
2341       F_8971       NaN     NaN    U_211731
2924      F_11575       NaN     NaN     U_37019
3252      F_22080       NaN     NaN    U_110965
6132      F_11575       NaN     NaN     U_21790
6585       F_2859       NaN     NaN      U_6511
10022     F_70569       NaN     NaN    U_163037
10046     F_54621       NaN     NaN    U_120146
10847     F_60124       NaN     NaN    U_134926
12426     F_70569       NaN     NaN    U_208878

In [17]:
df_Uid_data.isna().sum()

SYNTHETIC_U                           0
ORG_TYPE                              0
OKFS_NAME                             0
COMPANY_AGE_YEARS_GRADATION           0
ECO_MARK_LABEL                     4157
MAINOKVED_CODE                        0
MAINOKVED_NAME                        0
NEGATIVEMARK                          0
AMOUNT_WORKERS_FNS_GRADATION          0
AMOUNT_WORKERS_SPARK_GRADATION    85357
CL_TYPE                               0
CL_PRODUCT_RKO_MARK                   0
CL_PRODUCT_GAR_MARK                   0
CL_PRODUCT_LOA_MARK                   0
CL_PRODUCT_LEA_MARK                   0
CL_PRODUCT_DEP_MARK                   0
CL_PRODUCT_ZPP_MARK                   0
FTS_FLAG                              0
FTS_COUNTRY_NAME                  77179
FACTORING_MARK                        0
REVENUE_COMPANY                       0
GROUP_ID                              0
CITY                                  0
REGION                                0
dtype: int64

In [18]:
df_Uid_data.describe()

,NEGATIVEMARK,CL_PRODUCT_RKO_MARK,CL_PRODUCT_GAR_MARK,CL_PRODUCT_LOA_MARK,CL_PRODUCT_LEA_MARK,CL_PRODUCT_DEP_MARK,CL_PRODUCT_ZPP_MARK,FTS_FLAG,FACTORING_MARK,REVENUE_COMPANY
count,85525.000000,85525.000000,85525.000000,85525.000000,85525.000000,85525.000000,85525.000000,85525.000000,85525.000000,8.552500e+04
mean,0.129506,0.463759,0.032599,0.057819,0.175516,0.050079,0.309664,0.097796,0.002490,3.797200e+08
std,0.335761,0.498688,0.177585,0.233403,0.380410,0.218109,0.462358,0.297040,0.049843,1.425250e+09
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+03
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.835000e+05
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.358343e+07
75%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.401415e+08
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.055965e+11

In [19]:
df_Uid_payment.isna().sum()

BENEFICIARY    0
PAYER          0
PAY_AMT        0
PAY_CNT        0
dtype: int64

In [20]:
df_Uid_payment.describe()

            PAY_AMT       PAY_CNT
count  1.380585e+06  1.380585e+06
mean   4.055617e+07  1.775753e+01
std    1.814375e+09  1.363130e+02
min    1.000000e+03  1.000000e+00
25%    4.400000e+04  2.000000e+00
50%    2.120000e+05  5.000000e+00
75%    1.367000e+06  1.300000e+01
max    1.118581e+12  1.246710e+05

In [22]:
print(df_Fid_Uid.shape, df_Uid_data.shape, df_Uid_payment.shape) #Размер df_Fid_Uid<df_Uid_data ?

(12514, 4) (85525, 24) (1380585, 4)

In [31]:
print(df_Fid_Uid.duplicated().sum(), df_Uid_data.duplicated().sum(), df_Uid_payment.duplicated().sum())

0 0 1

In [46]:
df_Uid_payment[df_Uid_payment.duplicated(keep=False)] #Будто бы дубликаты тут вполне могут быть

        BENEFICIARY     PAYER  PAY_AMT  PAY_CNT
632617      U_84713  U_428697   8000.0        1
1283903     U_84713  U_428697   8000.0        1

In [37]:
df_Fid_Uid_data = pd.merge(df_Fid_Uid, df_Uid_data, how = 'inner', on = ['SYNTHETIC_U'])

In [38]:
df_Fid_Uid_data.isna().sum()

SYNTHETIC_F                          0
CITY_NAME                            0
RC_NAME                              0
SYNTHETIC_U                          0
ORG_TYPE                             0
OKFS_NAME                            0
COMPANY_AGE_YEARS_GRADATION          0
ECO_MARK_LABEL                     234
MAINOKVED_CODE                       0
MAINOKVED_NAME                       0
NEGATIVEMARK                         0
AMOUNT_WORKERS_FNS_GRADATION         0
AMOUNT_WORKERS_SPARK_GRADATION    4618
CL_TYPE                              0
CL_PRODUCT_RKO_MARK                  0
CL_PRODUCT_GAR_MARK                  0
CL_PRODUCT_LOA_MARK                  0
CL_PRODUCT_LEA_MARK                  0
CL_PRODUCT_DEP_MARK                  0
CL_PRODUCT_ZPP_MARK                  0
FTS_FLAG                             0
FTS_COUNTRY_NAME                  4041
FACTORING_MARK                       0
REVENUE_COMPANY                      0
GROUP_ID                             0
CITY                                 0
REGION                               0
dtype: int64

In [39]:
df_Fid_Uid_data.shape #Ещё и пересечение меньше Fid_Uid... Сэмплы Fid_Uid, не принадлежащие Uid_data, несут в себе только данные о местоположении физлиц... и то не факт. NaN из Fid_Uid можно удалить, полагаю. Восстановить вряд ли возможно.

(4629, 27)

In [105]:
df_Fid_Uid_ref = df_Fid_Uid.dropna(ignore_index = True)
df_Fid_Uid_ref

      SYNTHETIC_F        CITY_NAME          RC_NAME SYNTHETIC_U
0         F_64255         Мск "Юг"       МОСКОВСКИЙ    U_146717
1          F_2064             Омск        СИБИРСКИЙ     U_40653
2         F_67674           Москва       МОСКОВСКИЙ    U_155903
3         F_84228           Москва       МОСКОВСКИЙ    U_195486
4         F_63862  Санкт-Петербург  Санкт-Петербург    U_145713
...           ...              ...              ...         ...
12495     F_51582           Москва       МОСКОВСКИЙ    U_143489
12496     F_13670      Новосибирск        СИБИРСКИЙ     U_25938
12497     F_37000     Мск "Восток"       МОСКОВСКИЙ    U_108575
12498     F_75618           Казань       ПОВОЛЖСКИЙ    U_167353
12499     F_96401           Москва       МОСКОВСКИЙ    U_225393

[12500 rows x 4 columns]

In [45]:
Uids = np.unique(df_Uid_data['SYNTHETIC_U'].to_numpy())
Uids.shape #Дубликаты среди Uid_data? (~22 шт.?)

(85514,)

In [48]:
df_Uid_data[df_Uid_data[['SYNTHETIC_U']].duplicated(keep=False)] #Что? Может, Id забыли разные приписать? Попробую исправить

,SYNTHETIC_U,ORG_TYPE,OKFS_NAME,COMPANY_AGE_YEARS_GRADATION,ECO_MARK_LABEL,MAINOKVED_CODE,MAINOKVED_NAME,NEGATIVEMARK,AMOUNT_WORKERS_FNS_GRADATION,AMOUNT_WORKERS_SPARK_GRADATION,...,CL_PRODUCT_LEA_MARK,CL_PRODUCT_DEP_MARK,CL_PRODUCT_ZPP_MARK,FTS_FLAG,FTS_COUNTRY_NAME,FACTORING_MARK,REVENUE_COMPANY,GROUP_ID,CITY,REGION
85513,U_428697,КОММ_ОРГ,СОБСТВЕННОСТЬ ИНОСТРАННЫХ ГРАЖДАН И ЛИЦ БЕЗ ГР...,0-3,NaN,46.90,Торговля оптовая неспециализированная,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,23619981.0,group_91277_sb,г. Москва,Москва
85514,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,8-15,Бизнес в новой реальности,41.20,Строительство жилых и нежилых зданий,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,236263.0,group_7498_sb,г. Челябинск,Челябинская область
85515,U_428697,КОММ_ОРГ,СОБСТВЕННОСТЬ ИНОСТРАННЫХ ГРАЖДАН И ЛИЦ БЕЗ ГР...,0-3,NaN,46.45,Торговля оптовая парфюмерными и косметическими...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,57872.0,group_134696_sb,г. Москва,Москва
85516,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,8-15,Оптимизация,41.2,Строительство жилых и нежилых зданий,1.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,79177.0,group_134833_sb,г. Казань,Республика Татарстан
85517,U_428697,КОММ_ОРГ,СОБСТВЕННОСТЬ ИНОСТРАННЫХ ГРАЖДАН И ЛИЦ БЕЗ ГР...,0-3,NaN,47.91,Торговля розничная по почте или по информацион...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,46320658.0,group_92057_sb,г. Москва,Москва
85518,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,4-7,Бизнес в новой реальности,93.19,Деятельность в области спорта прочая,0.0,Менее 15,Менее 15,...,0.0,0.0,0.0,0.0,NaN,0.0,227010.0,group_9171_sb,г. Санкт-Петербург,Санкт-Петербург
85519,U_428697,КОММ_ОРГ,СОБСТВЕННОСТЬ ИНОСТРАННЫХ ГРАЖДАН И ЛИЦ БЕЗ ГР...,0-3,NaN,46.73,"Торговля оптовая лесоматериалами, строительным...",0.0,16-100,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,12881354.0,group_29468_sb,г. Москва,Москва
85520,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,8-15,Бизнес в новой реальности,52.29,"Деятельность вспомогательная прочая, связанная...",0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,51427.0,group_90099_sb,г. Самара,Самарская область
85521,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,0-3,NaN,46.73,"Торговля оптовая лесоматериалами, строительным...",0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,739757751.0,group_90293_sb,г. Москва,Москва
85522,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,16-25,Бизнес в новой реальности,68.32.1,Управление эксплуатацией жилого фонда за возна...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,44290.0,group_86361_sb,г. Тольятти,Самарская область
85523,U_428697,КОММ_ОРГ,СОБСТВЕННОСТЬ ИНОСТРАННЫХ ГРАЖДАН И ЛИЦ БЕЗ ГР...,0-3,NaN,47.91,Торговля розничная по почте или по информацион...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,95023024.0,group_92057_sb,г. Москва,Москва
85524,U_428697,КОММ_ОРГ,ЧАСТНАЯ СОБСТВЕННОСТЬ,8-15,Бизнес в новой реальности,68.20.2,Аренда и управление собственным или арендованн...,0.0,Менее 15,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,27577.0,group_42134_sb,г. Тольятти,Самарская область

In [85]:
Fid_Uids = np.unique(df_Fid_Uid['SYNTHETIC_U'].to_numpy())
Benef_Uids = np.unique(df_Uid_payment['BENEFICIARY'].to_numpy())
Payer_Uids = np.unique(df_Uid_payment['PAYER'].to_numpy())

In [115]:
Uidxs2chck = ['U_428'+str(k) for k in range(697, 709)]

In [116]:
for U in Uidxs2chck:
    print(f'{U}: {np.arange(Fid_Uids.size)[Fid_Uids == U]}')

U_428697: []
U_428698: []
U_428699: []
U_428700: []
U_428701: []
U_428702: []
U_428703: []
U_428704: []
U_428705: []
U_428706: []
U_428707: []
U_428708: []

In [122]:
for U in Uidxs2chck:
    print(f'{U}: {np.arange(Benef_Uids.size)[Benef_Uids == U]}')

U_428697: [89997]
U_428698: []
U_428699: []
U_428700: []
U_428701: []
U_428702: []
U_428703: []
U_428704: []
U_428705: []
U_428706: []
U_428707: []
U_428708: []

In [123]:
for U in Uidxs2chck:
    print(f'{U}: {np.arange(Payer_Uids.size)[Payer_Uids == U]}')

U_428697: [131543]
U_428698: []
U_428699: []
U_428700: []
U_428701: []
U_428702: []
U_428703: []
U_428704: []
U_428705: []
U_428706: []
U_428707: []
U_428708: []

In [124]:
for U in Uidxs2chck:
    print(f'{U}: {np.arange(Uids.size)[Uids == U]}')

U_428697: [70898]
U_428698: []
U_428699: []
U_428700: []
U_428701: []
U_428702: []
U_428703: []
U_428704: []
U_428705: []
U_428706: []
U_428707: []
U_428708: []

In [121]:
df_Uid_data_ref = df_Uid_data.copy()
Idxs2ref = np.arange(85513, 85525)
df_Uid_data_ref.update(pd.DataFrame({'SYNTHETIC_U':Uidxs2chck}, index = Idxs2ref))

In [143]:
Temp1 = df_Uid_payment[df_Uid_payment['BENEFICIARY'].isin(Uids)].reset_index(drop=True)
Temp2 = Temp1[Temp1['PAYER'].isin(Uids)].reset_index(drop=True)
Temp3 = df_Uid_payment[df_Uid_payment['PAYER'].isin(Uids)].reset_index(drop=True)
Temp4 = df_Uid_payment[~df_Uid_payment['BENEFICIARY'].isin(Uids)].reset_index(drop=True)
Temp4 = Temp4[Temp4['PAYER'].isin(Uids)].reset_index(drop=True)
print(Temp1.shape, Temp2.shape, Temp3.shape, Temp4.shape) #Среди оплаты существуют вхождения, не принадлежащие ни одной из известных из Uid_data компаний.

(971561, 4) (389396, 4) (798420, 4) (409024, 4)